<div id="footer">
  <ul class="address">
    <li>Taylor K. Spencer</li>
    <li>924 Hillside Drive</li>
    <li>Copper Canyon, TX 75077</li>
    <li>Email:&nbsp;<img src="shared/email-link.png" alt="Email address protected from spambots" onClick="javascript:location.href='mailto:taylorkspencer@gmail.com'" class="emailLink"/></li>
  </ul>
  <ul class="links">
    <li><a href="#top">Return to Top</a></li>
  </ul>
  <ul class="copyNotices">
    <li>This site uses the fonts <a href="https://aajohan.deviantart.com/art/Comfortaa-font-105395949">Comfortaa</a>, <a href="https://aajohan.deviantart.com/art/Comfortaa-font-105395949">Comfortaa Bold</a>, <a href="http://www.gust.org.pl/projects/e-foundry/latin-modern">LM Roman</a>, <a href="http://www.gust.org.pl/projects/e-foundry/latin-modern">LM Sans</a>, and <a href="http://www.gust.org.pl/projects/e-foundry/latin-modern">LM Mono</a>.</li>
    <ul>
      <li>Comfortaa and Comfortaa Bold are &copy; 2011 Johan Aakerlund and are licensed under the SIL Open Font License.</li>
      <li>LM Roman is &copy; 2003-2009 B. Jackowski and J. M. Nowacki and is licensed under the GUST Font License.</li>
      <li>LM Sans is &copy; 2003-2009 B. Jackowski and J. M. Nowacki and is licensed under the GUST Font License.</li>
      <li>LM Mono is &copy; 2003-2009 B. Jackowski and J. M. Nowacki and is licensed under the GUST Font License.</li>
    </ul>
  </ul>
</div>
