<div id="header">
  <a name="top"></a>
  <h1 class="primary"></h1>
  <ul class="social">
    <li><a href="extern.html?redir=linkedin" rel="me"><img src="shared/linkedin-banner.png" height="30" width="39" alt="Taylor Spencer on LinkedIn"/></a></li>
    <li><a href="extern.html?redir=github" rel="me"><img src="shared/github-banner.png" height="30" width="31" alt="Taylor Spencer on GitHub"/></a></li>
  </ul>
  <ul id="links"></ul>
</div>
