<div id="header">
  <a name="top"></a>
  <span class="primary"></span>
  <ul class="social">
    <li><a href="extern.html?redir=linkedin"><img src="shared/linkedin-banner.png" height="30" width="39" alt="Taylor Spencer on LinkedIn"/></a></li>
    <li><a href="extern.html?redir=github"><img src="shared/github-banner.png" height="30" width="31" alt="Taylor Spencer on GitHub"/></a></li>
  </ul>
  <ul id="links"></ul>
</div>
